quiet: true
skip-check:
  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_2
  # Ensure that a user for the container has been created
  - CKV_DOCKER_3
  # GitHub Actions workflow_dispatch inputs MUST be empty.
  - CKV_GHA_7
