# Unordered list style
MD004:
  style: dash

# Ordered list item prefix
MD029:
  style: one

# Link fragments should be valid [Context: "[`action.yml`](#page_facing_up-actionyml)"]
MD051: false

# Line length
MD013:
  code_blocks: false
