# Heading style
MD003:
  style: setext_with_atx

# Unordered list style
MD004:
  style: dash

# Line length
MD013:
  code_blocks: false

# Ordered list item prefix
MD029:
  style: one

    # Inline HTML
MD033:
  allowed_elements: [details, summary]

# Code block style
MD046:
  style: fenced

# Link fragments should be valid
# [Context: "[`action.yml`](#page_facing_up-actionyml)"]
MD051: false
