name: Greeting Workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to Greet
        required: true
        default: 'World'

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        id: print
        uses: alissa-huskey/hello-world-docker-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
      - name: Get the output time
        id: time
        run: 'echo ::notice file=greeting.yml,line=25::The time was: ${{ steps.print.outputs.time }}.'
